name: Lint Markdown

on:
  pull_request:
    branches: [main, staging, develop]
    paths:
      - "**/*.md"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint-markdown:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Run Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          config: .markdownlint.jsonc
          globs: |
            **/*.md
            !node_modules/
            !data/
